apiVersion: certmanager.k8s.io/v1alpha1
   kind: Issuer
   metadata:
     name: wp-letsencrypt-prod-issuer
   spec:
     acme:
       # The ACME server URL
       server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: beto2l@me.com
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: wp-letsencrypt-prod-issuer
       # Enable the HTTP-01 challenge provider
       http01: {}